version: '3.8'

services:
  bureau-service:
    build:
      context: ./bureau-service
      dockerfile: Dockerfile
    container_name: bureau-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/api/bureau/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  identidad-service:
    build:
      context: ./identidad-service
      dockerfile: Dockerfile
    container_name: identidad-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8082/api/identidad/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  scoring-service:
    build:
      context: ./scoring-service
      dockerfile: Dockerfile
    container_name: scoring-service
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8083/api/scoring/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  evaluacion-service:
    build:
      context: ./evaluacion-service
      dockerfile: Dockerfile
    container_name: evaluacion-service
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    environment:
      - BUREAU_SERVICE_URL=http://bureau-service:8081
      - IDENTIDAD_SERVICE_URL=http://identidad-service:8082
      - SCORING_SERVICE_URL=http://scoring-service:8083
    depends_on:
      bureau-service:
        condition: service_healthy
      identidad-service:
        condition: service_healthy
      scoring-service:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/evaluacion/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  microservices-network:
    driver: bridge
    name: microservices-network
